services:
  - type: web
    name: vagego-stream-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BASE_URL
        sync: false
      - key: PORT
        value: "8080"
      - key: ADMIN_SECRET
        sync: false
